config/routes.rb
Rails.application.routes.draw do
  get '/thanks' => 'pages#thanks'
  root 'signups#new'

  get '/history' => 'pages#history'
  get '/coffee' => 'pages#coffee'
  get '/contact' => 'pages#contact'

  get '/messages' => 'messages#index'
  get '/messages/new' => 'messages#new'
  post 'messages' => 'messages#create'
  
  resources :signups

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/signup.rb
class Signup < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	def index
		@messages = Message.all
	end

	def new
		@message = Message.new
	end

	def create
		@message = Message.new(message_params) 
  		
  		if @message.save 
    		redirect_to '/messages' 
  		else 
    	render 'new' 
  		end 
	end


	private 

  	def message_params 
    	params.require(:message).permit(:content) 
  	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def thanks
	end

	def history
	end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
	def new
		@signup = Signup.new
	end
	
	def create 
    @signup = Signup.new(signup_params)
    if @signup.save
      redirect_to '/thanks'
    end
  end 
  
  private 
  def signup_params
    params.require(:signup).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KopiLuwak</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/index.html.erb
<style>

.message{
	
	padding: 5px;
	background: lightgrey;
	margin-top: 10px;
}

</style>
<div class="header">
      <div class="container">
        <h1>Kopi Luwak</h1>
        <p>The secret of DELICIOUS coffee</p>
        <a class="btn" href="#">Learn More</a>
      </div>
    </div>

    <div class="nav">
      <div class="container">
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Farming Luwaks", history_path %></li> 
          <li><%= link_to "Coffee", coffee_path %></li>
          <li><%= link_to "Comment", messages_path %></li>
           <li><%= link_to "Contact", contact_path %></li>
        </ul>
      </div>
    </div>
</div>

<% @messages.each do |message| %> 
<div class="message"> 
  <p class="content"><%= message.content %></p> 
  <p class="time"><%= message.created_at %></p> 
</div> 
<% end %>
<div class="but">
<%= link_to 'New Message', "messages/new" %></div>

 <div class="footer">
      <div class="container">
        <p>&copy; Kopi Luwak International</p>
      </div>
 </div>

app/views/messages/new.html.erb
<style>

.message{
	padding: 5px;
	background: lightgrey;
	margin-top: 10px;
}
</style>
<div class="header">
      <div class="container">
        <h1>Kopi Luwak</h1>
        <p>The secret of DELICIOUS coffee</p>
        <a class="btn" href="#">Learn More</a>
      </div>
    </div>

    <div class="nav">
      <div class="container">
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Farming Luwaks", history_path %></li> 
          <li><%= link_to "Coffee", coffee_path %></li>
           <li><%= link_to "Comment", messages_path %></li>
           <li><%= link_to "Contact", contact_path %></li>
        </ul>
      </div>
    </div>
</div>

<%= form_for(@message) do |f| %>  
  <div class="field"> 
    <%= f.label :message %><br> 
    <%= f.text_area :content %> 
  </div> 
  <div class="actions"> 
    <%= f.submit "Create" %> 
  </div> 
<% end %>

 <div class="footer">
      <div class="container">
        <p>&copy; Kopi Luwak International</p>
      </div>
    </div>

app/views/pages/coffee.html.erb
<style>
  .container_fluid{
    padding: 30px;
  }

.image img{
  height: 300px;
}

</style>
<div class="header">
      <div class="container">
        <h1>Kopi Luwak</h1>
        <p>The secret of DELICIOUS coffee</p>
        <a class="btn" href="#">Learn More</a>
      </div>
    </div>

    <div class="nav">
      <div class="container">
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Farming Luwaks", history_path %></li> 
          <li><%= link_to "Coffee", coffee_path %></li>
           <li><%= link_to "Comment", messages_path %></li>
           <li><%= link_to "Contact", contact_path %></li>
        </ul>
      </div>
    </div>
</div>

<div class="container_fluid">
  <h2>What is Kopi Luwak Coffee?</h2>
  <p>Kopi Luwak, or what many people like to call, cat poop coffee, are coffee beans that have been digested and defecated by Asian Palm Civets (Indonesian jungle cats). When the Asian Palm Civets eat the berries, the gastric juices in the cat seep into the beans thus creating an abundance of amino acids. This then reduces the acidity of the coffee thus giving the Kopi Luwak it’s unique taste and aroma. This entire digestive process is also what gives the Kopi Luwak a very non-bitter taste and smooth feel. Many coffee drinkers find this to be the most positive thing about drinking Kopi Luwak coffee</p><br><br>

    <img src="http://catpoopcoffeeinc.com/wp-content/uploads/2013/03/what-is-kopi-luwak-coffee.jpg" alt="coffee" ><br /><br />
    <p>During the 1700s, Dutch colonists created coffee plantations in the Dutch East Indies islands of Sumatra and Java. Most of this coffee planted was of Arabica variety, which at the time came from the Middle Eastern country of Yemen.</p>
    <p>While the Dutch inhabited Sumatra and Java, the colonists used native Indonesian farmers to work the coffee plantations and pick coffee fruits for production. However, the Dutch colonists prohibited the Indonesian famers to pick and harvest the coffee fruits for their own personal use. As a result, the Indonesian farmers discovered a new way to enjoy and drink coffee. The Indonesian farmers soon discovered that the Asian Palm Civet ate the Arabica coffee fruits and left the coffee beans undigested in their poop.</p><br><br>
    <div class="image">
      <img src="http://www.boxnewsbox.com/wp-content/uploads/2015/01/luwak-dropping.jpg" alt="coffee">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    
       <img src="https://balikopiluwak.files.wordpress.com/2010/04/kopi-luwak-1.jpg" alt="coffee">
    </div>
    <br>
    <p>So what the native farmers did was collect the coffee beans from the poop, cleaned them, roasted them, and brewed their own coffee.  As more and more Indonesian farmers began to brew Kopi Lowak (also known as civet coffee), the aroma soon caught the attention of the Dutch colonists and plantation owners. When this happened, Kopi Luwak quickly became the favorite coffee drink of choice for both natives and the Dutch colonists.</p><br />

    <img src="http://www.sixinseoul.com/uploads/6/4/3/5/643559/4715798_orig.jpg" alt="coffee"><br /><br />
    <p>However, since the process of Kopi Luwak was very time consuming and scarce, Kopi Luwak became very pricey, thus making it the most expensive coffee in the world in it’s time. And it still is today!</p>
</div>


<div class="footer">
      <div class="container">
        <p>&copy; Kopi Luwak International</p>
      </div>
    </div>

app/views/pages/contact.html.erb
  <title></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>




<div class="header">
      <div class="container">
        <h1>Kopi Luwak</h1>
        <p>The secret of DELICIOUS coffee</p>
        <a class="btn" href="#">Learn More</a>
      </div>
    </div>

    <div class="nav">
      <div class="container">
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Farming Luwaks", history_path %></li> 
          <li><%= link_to "Coffee", coffee_path %></li>
           <li><%= link_to "Comment", messages_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
        </ul>
      </div>
    </div>
</div>



<div class="container-fluid bg-grey">
  <h2 class="text-center">CONTACT</h2>
  <div class="row">
    <div class="col-sm-5">
      <p>Contact us and we'll get back to you within 24 hours.</p>
      <p><span class="glyphicon glyphicon-map-marker"></span> San Francisco, California</p>
      <p><span class="glyphicon glyphicon-phone"></span>(415) 451-9812</p>
      <p><span class="glyphicon glyphicon-envelope"></span>jon@kopiluka.com</p> 
    </div>
    <div class="col-sm-7">
      <div class="row">
        <div class="col-sm-6 form-group">
          <input class="form-control" id="name" name="name" placeholder="Name" type="text" required>
        </div>
        <div class="col-sm-6 form-group">
          <input class="form-control" id="email" name="email" placeholder="Email" type="email" required>
        </div>
      </div>
      <textarea class="form-control" id="comments" name="comments" placeholder="Comment" rows="5"></textarea><br>
      <div class="row">
        <div class="col-sm-12 form-group">
          <button class="btn btn-default pull-right" type="submit">Send</button>
        </div>
      </div> 
    </div>
  </div>
</div>

app/views/pages/history.html.erb
<div class="header">
      <div class="container">
        <h1>Kopi Luwak</h1>
        <p>The secret of DELICIOUS coffee</p>
        <a class="btn" href="#">Learn More</a>
      </div>
    </div>

    <div class="nav">
      <div class="container">
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Farming Luwaks", history_path %></li> 
          <li><%= link_to "Coffee", coffee_path %></li>
           <li><%= link_to "Comment", messages_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
        </ul>
      </div>
    </div>
</div>
    
<div class="container"><br>
  <h1>History of Kopi Luwak Coffee</h1><br>
    <p>Kopi Luwak Coffee is a high quality coffee, processed by the Asian Palm Civet.</p><br>
    <p><h2>Nowadays it’s produced in Indonesia, the Philippines and Vietnam. In Vietnam it’s called “Weasel Coffee” and in the Philippines they call it “Civet Coffee”</h2><p><br>
      <p>The raw coffee beans are eaten by Asian Palm Civets. These are little animals living in the forests of southeast asia.
In these civets, special enzymes remove the bitterness of the coffee beans which results in a smooth tasting, not-bitter, rich tasting, high quality coffee. Because of that the coffee has it’s unique flavor.</p><br />

<div class="container_fluid">
  <img src="https://i.guim.co.uk/img/static/sys-images/Guardian/Pix/pictures/2014/9/18/1411054191048/6e9c497b-1da8-49ff-ae14-81856424606e-2060x1236.jpeg?w=620&q=85&auto=format&sharp=10&s=2b810f05b87c92a67cae9e43b237b93d" alt="Civet cat">
</div><br>

    <p>The name comes from the native language of Indonesia: “Kopi” means “Coffee” and “Luwak” means “Asian Palm Civet”.</p><br />
    <p>It’s also called “Civet Coffee” (in the Philippines) and “Weasel Coffee” (in Vietnam).</p><br />
<div class="container_fluid">
  <img src="http://media.npr.org/assets/img/2013/09/02/89740957_wide-10b7e4f3c1daad8ac411a746a5ab4ca637da4b74-s300-c85.jpg" alt="Civet cat">
</div><br>

    <p>Bali, Sumatra and Jakarta were the places where the coffee came up first.
In the Indonesian colonial times, the dutch harvested the coffee beans of the plantations. The farmers weren’t allowed to harvest them themselves. So they didn’t have a product to sell anymore. These were hard times for the farmers, so they started collecting the coffee beans, they found on the floor (in the droppings of the Asian Palm Civets).</p><br />

<div class="container_fluid">
  <img src="http://2.bp.blogspot.com/-pvR9OdVfUgw/TqdcL-eBKGI/AAAAAAAABbI/1giMdSqW-_A/s1600/civet-cat0311.jpg" alt="Civet cat" >
  </div><br>
    <p>That’s how the farmers found out that the coffee tasted better than the “normal” coffee, they usually drank.</p><br />
    <p>In the late 20th century and in the early 21st century, this type of coffee became more and more popular in western countries and nowadays it is consumed by many gourmets around the globe.</p><br>
</div>
<div class="footer">
      <div class="container">
        <p>&copy; Kopi Luwak International</p>
      </div>
    </div>

app/views/pages/thanks.html.erb
    <div class="header">
      <div class="container">
        <h1>Thank you for signing up. We'll keep you posted.</h1>
       
      </div>
    </div>

    <div class="footer">
      <div class="container">
        <p>&copy; Kopi Luwak International</p>
      </div>
    </div>

app/views/signups/new.html.erb
    <div class="header">
      <div class="container">
        <h1>Kopi Luwak</h1>
        <p>The secret of DELICIOUS coffee</p>
        <a class="btn" href="#">Learn More</a>
      </div>
    </div>

    <div class="nav">
      <div class="container">
        <ul>
           <li><%= link_to "Home", root_path %></li>
           <li><%= link_to "Farming Luwaks", history_path %></li> 
           <li><%= link_to "Coffee", coffee_path %></li>
           <li><%= link_to "Comment", messages_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
        </ul>
      </div>
    </div>

    <div class="main">
      <div class="container">
        <img src="http://www.sciencebuzz.org/sites/default/files/images/800px-Palmenroller-drawing.jpg" >
        <h2>The Best Cat Poop Coffee (Kopi Luwak)</h2><br>
        <p> Officially known at Kopi Luwak, is a possibly the world’s most unique coffee </p>
        <p>While also being the world’s most expensive coffee, cat poop coffee (kopi luwak) has the craziest, if not the strangest production and manufacturing process around, thus giving it a one of a kind flavor.</p>
        <p>The coffee bean is literally picked out of the poop of the cat (an asian civet) that eats the coffee berries. ...</p>
      </div>
    </div>

    <div class="jumbotron">
      <div class="container">
        <h2>Stay Connected</h2>
        <p>More information...</p>
        
        <%= form_for(@signup) do |signup| %><br/>
        <%= signup.text_field:email, :placeholder => "Email" %><br>
        <%= signup.submit "Submit" %>
      </div>
      <% end %>
    </div>

    <div class="footer">
      <div class="container">
        <p>&copy; Kopi Luwak International</p>
      </div>
    </div>